### ISSUE TITLE
Can not add DifferentialEquations

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaDiffEq/DiffEqDocs.jl#333] opened 2020-02-24 12:17 UTC
I tried to add the latest version of DifferentialEquations and I receive the following Error:
pkg> st
    Status `C:\Users\Chris\.julia\environments\v1.3\Project.toml`
  [7d9fca2a] Arpack v0.4.0
  [c52e3926] Atom v0.12.5
  [1e616198] COSMO v0.6.0
  [a076750e] CPLEX v0.6.3
  [9961bab8] Cbc v0.6.6
  [e2554f3b] Clp v0.7.1
  [f65535da] Convex v0.12.4
  [60bf3e95] GLPK v0.12.1
  [2e9cd046] Gurobi v0.7.5
  [a98d9a8b] Interpolations v0.12.8
  [b6b21f68] Ipopt v0.6.1
  [42fd0dbc] IterativeSolvers v0.8.1
  [4076af6c] JuMP v0.21.1
  [2ddba703] Juniper v0.6.1
  [e5e0dc1b] Juno v0.8.0
  [67920dd8] KNITRO v0.8.0
  [7a12625a] LinearMaps v2.6.1
  [33e6dc65] MKL v0.2.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [429524aa] Optim v0.20.1
  [91a5bcdd] Plots v0.29.1
  [d330b81b] PyPlot v2.8.2
  [82193955] SCIP v0.9.1
  [c946c3f1] SCS v0.6.6
  [c3572dad] Sundials v3.8.3
  [9e70acf3] Xpress v0.10.0
  [37e2e46d] LinearAlgebra

(v1.3) pkg> add DifferentialEquations
 Resolving package versions...
  Updating `C:\Users\Chris\.julia\environments\v1.3\Project.toml`
  [0c46a032] + DifferentialEquations v6.11.0
  Updating `C:\Users\Chris\.julia\environments\v1.3\Manifest.toml`
  [79e6a3ab] + Adapt v1.0.1
  [ec485272] + ArnoldiMethod v0.0.4
  [4c555306] + ArrayLayouts v0.1.5
  [aae01518] + BandedMatrices v0.14.3
  [764a87c0] + BoundaryValueDiffEq v2.4.0
  [d360d2e6] + ChainRulesCore v0.6.1
  [bcd4f6db] + DelayDiffEq v5.21.0
  [2b5f629d] + DiffEqBase v6.17.3
  [459566f4] + DiffEqCallbacks v2.12.0
  [5a0ffddc] + DiffEqFinancial v2.2.1
  [c894b116] + DiffEqJump v6.5.0
  [77a26b50] + DiffEqNoiseProcess v3.9.0
  [055956cb] + DiffEqPhysics v3.5.0
  [0c46a032] + DifferentialEquations v6.11.0
  [c619ae07] + DimensionalPlotRecipes v1.1.0
  [ffbed154] + DocStringExtensions v0.8.1
  [d4d017d3] + ExponentialUtilities v1.6.0
  [069b7b12] + FunctionWrappers v1.0.0
  [01680d73] + GenericSVD v0.2.2
  [d25df0c9] + Inflate v0.1.1
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [093fc24a] + LightGraphs v1.3.1
  [46d2c3a1] + MuladdMacro v0.2.2
  [f9640e96] + MultiScaleArrays v1.6.0
  [2774e3e8] + NLsolve v4.3.0
  [1dea7af3] + OrdinaryDiffEq v5.29.0
  [e409e4f3] + PoissonRandom v0.4.0
  [e6cf234a] + RandomNumbers v1.4.0
  [731186ca] + RecursiveArrayTools v2.1.0
  [f2c3362d] + RecursiveFactorization v0.1.0
  [ae5879a3] + ResettableStacks v1.0.0
  [f2b01f46] + Roots v0.8.4
  [699a6c99] + SimpleTraits v0.9.1
  [47a9eef4] + SparseDiffTools v1.3.3
  [9672c7b4] + SteadyStateDiffEq v1.5.0
  [789caeaf] + StochasticDiffEq v6.19.1
  [c3572dad] + Sundials v3.8.3
  [3783bdb8] + TableTraits v1.0.0
  [19fa3120] + VertexSafeGraphs v0.1.1
  [700de1a5] + ZygoteRules v0.2.0

(v1.3) pkg> ^C

julia> using DifferentialEquations
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
ERROR: LoadError: InitError: could not load library "C:\Users\Chris\.julia\artifacts\77374b3a2aebcba1d77004710226d8410ce4ae02\bin\libopenspecfun.dll"
The specified module could not be found.

Stacktrace:
 [1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at C:\Julia-1.3.1\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109
 [2] dlopen at C:\Julia-1.3.1\share\julia\stdlib\v1.3\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
 [3] __init__() at C:\Users\Chris\.julia\packages\OpenSpecFun_jll\XrUb6\src\wrappers\x86_64-w64-mingw32-libgfortran5.jl:35
 [4] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692
 [5] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:776
 [6] _require(::Base.PkgId) at .\loading.jl:1001
 [7] require(::Base.PkgId) at .\loading.jl:922
 [8] require(::Module, ::Symbol) at .\loading.jl:917
 [9] include at .\boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1105
 [11] include(::Module, ::String) at .\Base.jl:31
 [12] top-level scope at none:2
 [13] eval at .\boot.jl:330 [inlined]
 [14] eval(::Expr) at .\client.jl:425
 [15] top-level scope at .\none:3
during initialization of module OpenSpecFun_jll
in expression starting at C:\Users\Chris\.julia\packages\SpecialFunctions\5QYEE\src\SpecialFunctions.jl:3
ERROR: LoadError: Failed to precompile SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] to C:\Users\Chris\.julia\compiled\v1.3\SpecialFunctions\78gOt_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Chris\.julia\packages\ForwardDiff\vt5F1\src\ForwardDiff.jl:9
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to C:\Users\Chris\.julia\compiled\v1.3\ForwardDiff\k0ETY_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Chris\.julia\packages\NLSolversBase\mGaJg\src\NLSolversBase.jl:5
ERROR: LoadError: Failed to precompile NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] to C:\Users\Chris\.julia\compiled\v1.3\NLSolversBase\NEDD6_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Chris\.julia\packages\NLsolve\ZBTu4\src\NLsolve.jl:6
ERROR: LoadError: Failed to precompile NLsolve [2774e3e8-f4cf-5e23-947b-6d7e65073b56] to C:\Users\Chris\.julia\compiled\v1.3\NLsolve\KFCNP_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Chris\.julia\packages\SteadyStateDiffEq\q0UMK\src\SteadyStateDiffEq.jl:6
ERROR: LoadError: Failed to precompile SteadyStateDiffEq [9672c7b4-1e72-59bd-8a11-6ac3964bc41f] to C:\Users\Chris\.julia\compiled\v1.3\SteadyStateDiffEq\lsCSw_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Chris\.julia\packages\DifferentialEquations\hc2aQ\src\DifferentialEquations.jl:9
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to C:\Users\Chris\.julia\compiled\v1.3\DifferentialEquations\UQdwS_F0o0v.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917

Can anyone help
PS: I also tried to install V6.10.1 but I received the same error
Chris Nabold

**Comment by giordano** [comment] 2020-02-24 14:25
Hi Chris, how did you install Julia?  Could you also please the output of
```julia
using Libdl
filter!(x -> occursin("gfortran", x) || occursin("gcc_s", x) || occursin("msvcrt", x) || occursin("KERNEL32", x), dllist())
```

**Comment by ChrisNabold** [comment] 2020-02-24 15:58
Hi Mosé

 

After some trials I found the culprit:

DifferentialEquations.jl does not like if MKL.jl is installed.

 

I installed a clean Julia with DifferentialEquations

]add DifferentialEquations

 

using DifferentialEquations -> ok

]add MKL

using MKL -> ok

using DifferentialEquations -> error

 

Thank you for your help

Chris Nabold

**Comment by ChrisRackauckas** [comment] 2020-02-24 16:00
DiffEq doesn't care about MKL, so it must be SpecialFunctions.jl?

**Comment by giordano** [comment] 2020-02-24 16:01
Could you please post the output of
```julia
using Libdl
filter!(x -> occursin("gfortran", x) || occursin("gcc_s", x) || occursin("msvcrt", x) || occursin("KERNEL32", x), dllist())
```
anyway?

**Comment by ChrisNabold** [comment] 2020-02-24 16:28
Dear Mosé

 

The requested output:

 

julia> using Libdl

 

julia> filter!(x -> occursin("gfortran", x) || occursin("gcc_s", x) || occursin("msvcrt", x) || occursin("KERNEL32", x), dllist())

4-element Array{String,1}:

"C:\\WINDOWS\\System32\\KERNEL32.DLL"

"C:\\WINDOWS\\System32\\msvcrt.dll"

"C:\\Julia-1.3.1\\bin\\libgcc_s_seh-1.dll"

"C:\\Julia-1.3.1\\bin\\libgfortran-4.dll"

 

julia> using DifferentialEquations  -> ok

 

After MKL is installed using DifferentialEquations no longer work

 

After ]add https://github.com/JuliaComputing/MKL.jl

Using LinearAlgebra

:mkl

 

The error might be in LinearALgebra

**Comment by giordano** [comment] 2020-02-24 16:32
That is weird.  What's the output of
```julia
using Pkg.BinaryPlatforms
platform_key_abi()
```
?

**Comment by ChrisNabold** [comment] 2020-02-24 16:47
The output is: 

julia> using Pkg.BinaryPlatforms

 

julia> platform_key_abi()

Windows(:x86_64, compiler_abi=CompilerABI(libgfortran_version=v"4.0.0", cxxstring_abi=:cxx11))

 

Please obs: when MKL was installed the gfortran library is changed to x86-64-w64-mingw32-libgfortran5.jl

 

I hope you manage to find the problem. Best wishes!

 

Chris

**Comment by giordano** [comment] 2020-02-25 09:50
This a duplicate of https://github.com/JuliaMath/SpecialFunctions.jl/issues/192

**Comment by ChrisRackauckas** [comment] 2020-02-25 14:13
Thanks for figuring that out. I hope you guys find a solution there!

**Closed** 2020-02-25 14:12 UTC

**Comment by giordano** [comment] 2020-02-25 14:20
We probably have an option, just didn't try it out into the wild, yet
